### Consider the below code to answer further questions:

```py
import numpy as np
list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
array_list = np.array(object = list_)
```


In [1]:
import numpy as np
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

### Q1. Is there any difference in the data type of variables `list_` and `array_list`? If there is then write a code to print the data types of both the variables.


In [8]:
print('Data Type of list_ :', type(list_[0]))
print('Data Type of array_list :', array_list.dtype)

Data Type of list_ : <class 'str'>
Data Type of array_list : <U1


### Q2. Write a code to print the data type of each and every element of both the variables `list_` and `array_list`.


In [15]:
# For list_ variable
for i in list_:
    print(f'Data Type of {i} list_:', type(i))

print('--+--' * 10)

for j in array_list:
    print(f'Data Type of {j} in array_list:', type(j))


Data Type of 1 list_: <class 'str'>
Data Type of 2 list_: <class 'str'>
Data Type of 3 list_: <class 'str'>
Data Type of 4 list_: <class 'str'>
Data Type of 5 list_: <class 'str'>
--+----+----+----+----+----+----+----+----+----+--
Data Type of 1 in array_list: <class 'numpy.str_'>
Data Type of 2 in array_list: <class 'numpy.str_'>
Data Type of 3 in array_list: <class 'numpy.str_'>
Data Type of 4 in array_list: <class 'numpy.str_'>
Data Type of 5 in array_list: <class 'numpy.str_'>


### Q3. Considering the following changes in the variable, `array_list`:

```py
array_list = np.array(object = list_, dtype = int)
```

### Will there be any difference in the data type of the elements present in both the variables, `list_` and `array_list`? If so then print the data types of each and every element present in both the variables, `list_` and `arra_list`.


In [16]:
# Changes in array_list variable
array_list = np.array(object = list_, dtype = int)

In [17]:
# For list_ variable
for i in list_:
    print(f'Data Type of {i} list_:', type(i))

print('--+--' * 10)

for j in array_list:
    print(f'Data Type of {j} in array_list:', type(j))


Data Type of 1 list_: <class 'str'>
Data Type of 2 list_: <class 'str'>
Data Type of 3 list_: <class 'str'>
Data Type of 4 list_: <class 'str'>
Data Type of 5 list_: <class 'str'>
--+----+----+----+----+----+----+----+----+----+--
Data Type of 1 in array_list: <class 'numpy.int64'>
Data Type of 2 in array_list: <class 'numpy.int64'>
Data Type of 3 in array_list: <class 'numpy.int64'>
Data Type of 4 in array_list: <class 'numpy.int64'>
Data Type of 5 in array_list: <class 'numpy.int64'>



#### Consider the below code to answer further questions:

```py
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
```


In [18]:
import numpy as np
num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

### Q4. Write a code to find the following characteristics of variable `num_array`:

1. shape
2. size


In [20]:
print('1. Shape :', num_array.shape)
print('2. Size :', num_array.size)

1. Shape : (2, 3)
2. Size : 6


### Q5. Write a code to create numpy array of `3*3` matrix containing zeros only, using a numpy array creation function.

> `Hint:` The size of the array will be `9` and the shape will be `(3,3)`.


In [21]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### Q6. Create an identity matrix of shape `(5,5)` using numpy functions?

> `Hint:` An identity matrix is a matrix containing `1` diagonally and other elements will be `0`.


In [22]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [24]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])